export const RESPONSE_CODE = {
  SUCCESS: "SUCCESS",
  INVALID_REQUEST: "INVALID_REQUEST",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  SERVER_ERROR: "SERVER_ERROR",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
};
